/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'surface-tint': '#4ae176',
        'secondary': '#ff716a',
        'surface': '#070d1f',
        'on-surface-variant': '#96a9e6',
        'surface-container-low': '#09122b',
        'error-dim': '#bb5551',
        'background': '#070d1f',
        'on-primary-fixed': '#004a1d',
        'on-secondary-container': '#ffa9a2',
        'outline-variant': '#32457c',
        'on-primary-container': '#56eb7f',
        'on-error-container': '#ff9993',
        'inverse-on-surface': '#4f5469',
        'surface-variant': '#0a2257',
        'surface-container-highest': '#0a2257',
        'on-tertiary-fixed-variant': '#565e6b',
        'error': '#ee7d77',
        'tertiary-dim': '#d1d7e7',
        'surface-container-high': '#0b1d48',
        'tertiary-fixed': '#dfe5f6',
        'surface-bright': '#082768',
        'primary-fixed-dim': '#5bf083',
        'surface-container': '#0a1839',
        'on-error': '#490106',
        'surface-dim': '#070d1f',
        'outline': '#6073ad',
        'on-tertiary-fixed': '#3a414e',
        'primary-container': '#005321',
        'secondary-fixed': '#ffdad7',
        'secondary-fixed-dim': '#ffc7c2',
        'on-tertiary-container': '#4d5461',
        'on-surface': '#dfe4ff',
        'on-background': '#dfe4ff',
        'primary-dim': '#38d36a',
        'on-secondary': '#490005',
        'surface-container-lowest': '#000000',
        'secondary-container': '#7d000f',
        'error-container': '#7f2927',
        'tertiary-container': '#dfe5f6',
        'inverse-surface': '#faf8ff',
        'on-primary-fixed-variant': '#006a2d',
        'tertiary': '#f0f3ff',
        'on-secondary-fixed': '#850010',
        'on-tertiary': '#555c69',
        'tertiary-fixed-dim': '#d1d7e7',
        'on-primary': '#004b1e',
        'on-secondary-fixed-variant': '#b51621',
        'inverse-primary': '#006e2f',
        'secondary-dim': '#ff716a',
        'primary-fixed': '#6bff8f',
        'primary': '#4ae176',
      },
      fontFamily: {
        'headline': ['Space Grotesk', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
        'label': ['Inter', 'sans-serif'],
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
        '2xl': '1rem',
        '3xl': '1.5rem',
      },
    },
  },
  plugins: [],
}
